/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_tetris_free: (a: number, b: number) => void;
export const tetris_new: (a: number, b: number) => number;
export const tetris_start: (a: number) => void;
export const tetris_pause: (a: number) => void;
export const tetris_unpause: (a: number) => void;
export const tetris_is_paused: (a: number) => number;
export const tetris_move_left: (a: number) => void;
export const tetris_move_right: (a: number) => void;
export const tetris_move_down: (a: number) => number;
export const tetris_drop: (a: number) => void;
export const tetris_rotate_left: (a: number) => void;
export const tetris_rotate_right: (a: number) => void;
export const tetris_update_clearing_animation: (a: number, b: number) => void;
export const tetris_draw: (a: number) => void;
export const tetris_draw_next: (a: number, b: number, c: number) => void;
export const tetris_get_score: (a: number) => number;
export const tetris_is_game_over: (a: number) => number;
export const tetris_get_cleared_lanes: (a: number) => number;
export const tetris_get_tetris_count: (a: number) => number;
export const tetris_get_triple_count: (a: number) => number;
export const tetris_get_double_count: (a: number) => number;
export const tetris_get_single_count: (a: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_export_2: WebAssembly.Table;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_start: () => void;
